"""research layer

Revision ID: 0003_research_layer
Revises: 0002_fix_fx_cash_legs
Create Date: 2026-08-24 10:04:07.171308
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0003_research_layer'
down_revision = '0002_fix_fx_cash_legs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_frequency', sa.String(length=30), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_investment_ticker')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index('ix_investment_instrument', ['instrument_id'], unique=False)
        batch_op.create_index('ix_investment_next_review', ['next_review_date'], unique=False)
        batch_op.create_index('ix_investment_status', ['status'], unique=False)

    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('potential_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.create_index('ix_catalyst_expected', ['expected_date'], unique=False)
        batch_op.create_index('ix_catalyst_investment', ['investment_id'], unique=False)

    op.create_table('investment_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('direction_good', sa.String(length=10), nullable=True),
    sa.Column('thesis_relevance', sa.Text(), nullable=True),
    sa.Column('source_preference', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id', 'name', name='uq_kpi_investment_name')
    )
    with op.batch_alter_table('investment_kpis', schema=None) as batch_op:
        batch_op.create_index('ix_kpi_investment', ['investment_id'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index('ix_risk_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_risk_status', ['status'], unique=False)

    op.create_table('theses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.create_index('ix_thesis_investment', ['investment_id'], unique=False)

    op.create_table('valuation_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('reference_currency', sa.String(length=10), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_models', schema=None) as batch_op:
        batch_op.create_index('ix_valuation_investment', ['investment_id'], unique=False)

    op.create_table('kpi_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['investment_kpis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_id', 'period', 'source', name='uq_kpi_obs_period_source')
    )
    with op.batch_alter_table('kpi_observations', schema=None) as batch_op:
        batch_op.create_index('ix_kpi_obs_kpi', ['kpi_id'], unique=False)

    op.create_table('thesis_breakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis_breakers', schema=None) as batch_op:
        batch_op.create_index('ix_breaker_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_breaker_status', ['status'], unique=False)

    op.create_table('thesis_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('reason_for_revision', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('core_thesis', sa.Text(), nullable=True),
    sa.Column('variant_perception', sa.Text(), nullable=True),
    sa.Column('market_expectation', sa.Text(), nullable=True),
    sa.Column('our_expectation', sa.Text(), nullable=True),
    sa.Column('why_market_may_be_wrong', sa.Text(), nullable=True),
    sa.Column('expected_return_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('time_horizon', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_from_decision_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['previous_version_id'], ['thesis_versions.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'version_number', name='uq_thesis_version_number')
    )
    with op.batch_alter_table('thesis_versions', schema=None) as batch_op:
        batch_op.create_index('ix_thesis_version_thesis', ['thesis_id'], unique=False)

    op.create_table('valuation_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('time_horizon_months', sa.Integer(), nullable=True),
    sa.Column('expected_dividends', sa.Float(), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['valuation_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'scenario_name', name='uq_scenario_model_name')
    )
    with op.batch_alter_table('valuation_scenarios', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_model', ['model_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=15), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('thesis_version_id', sa.Integer(), nullable=True),
    sa.Column('amends_decision_id', sa.Integer(), nullable=True),
    sa.Column('instrument_price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('cash_value', sa.Float(), nullable=True),
    sa.Column('position_quantity_before', sa.Float(), nullable=True),
    sa.Column('position_weight_before', sa.Float(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('intended_position_change', sa.Text(), nullable=True),
    sa.Column('actual_position_change', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('time_horizon', sa.String(length=50), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('alternative_considered', sa.Text(), nullable=True),
    sa.Column('key_risks', sa.Text(), nullable=True),
    sa.Column('what_would_make_this_wrong', sa.Text(), nullable=True),
    sa.Column('information_available_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amends_decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decision_decided_at', ['decided_at'], unique=False)
        batch_op.create_index('ix_decision_investment', ['investment_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('thesis_version_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('source_published_at', sa.DateTime(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('reliability', sa.String(length=10), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_direction', ['direction'], unique=False)
        batch_op.create_index('ix_evidence_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_evidence_target', ['target_type', 'target_id'], unique=False)

    op.create_table('red_team_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('thesis_version_id', sa.Integer(), nullable=True),
    sa.Column('argument', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('red_team_entries', schema=None) as batch_op:
        batch_op.create_index('ix_redteam_investment', ['investment_id'], unique=False)

    op.create_table('thesis_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('introduced_in_version_id', sa.Integer(), nullable=True),
    sa.Column('kpi_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('expected_min', sa.Float(), nullable=True),
    sa.Column('expected_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('time_horizon', sa.String(length=50), nullable=True),
    sa.Column('breaker_condition', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['introduced_in_version_id'], ['thesis_versions.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['investment_kpis.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis_assumptions', schema=None) as batch_op:
        batch_op.create_index('ix_assumption_status', ['status'], unique=False)
        batch_op.create_index('ix_assumption_thesis', ['thesis_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_condition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_prediction_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_prediction_resolution_date', ['resolution_date'], unique=False)
        batch_op.create_index('ix_prediction_status', ['status'], unique=False)

    op.create_table('premortems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('thesis_version_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('early_warning_signs', sa.Text(), nullable=True),
    sa.Column('possible_mitigation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['thesis_version_id'], ['thesis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('premortems', schema=None) as batch_op:
        batch_op.create_index('ix_premortem_investment', ['investment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premortems', schema=None) as batch_op:
        batch_op.drop_index('ix_premortem_investment')

    op.drop_table('premortems')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_prediction_status')
        batch_op.drop_index('ix_prediction_resolution_date')
        batch_op.drop_index('ix_prediction_investment')

    op.drop_table('predictions')
    with op.batch_alter_table('thesis_assumptions', schema=None) as batch_op:
        batch_op.drop_index('ix_assumption_thesis')
        batch_op.drop_index('ix_assumption_status')

    op.drop_table('thesis_assumptions')
    with op.batch_alter_table('red_team_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_redteam_investment')

    op.drop_table('red_team_entries')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_target')
        batch_op.drop_index('ix_evidence_investment')
        batch_op.drop_index('ix_evidence_direction')

    op.drop_table('evidence')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_investment')
        batch_op.drop_index('ix_decision_decided_at')

    op.drop_table('decisions')
    with op.batch_alter_table('valuation_scenarios', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_model')

    op.drop_table('valuation_scenarios')
    with op.batch_alter_table('thesis_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_thesis_version_thesis')

    op.drop_table('thesis_versions')
    with op.batch_alter_table('thesis_breakers', schema=None) as batch_op:
        batch_op.drop_index('ix_breaker_status')
        batch_op.drop_index('ix_breaker_investment')

    op.drop_table('thesis_breakers')
    with op.batch_alter_table('kpi_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_kpi_obs_kpi')

    op.drop_table('kpi_observations')
    with op.batch_alter_table('valuation_models', schema=None) as batch_op:
        batch_op.drop_index('ix_valuation_investment')

    op.drop_table('valuation_models')
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.drop_index('ix_thesis_investment')

    op.drop_table('theses')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_status')
        batch_op.drop_index('ix_risk_investment')

    op.drop_table('risks')
    with op.batch_alter_table('investment_kpis', schema=None) as batch_op:
        batch_op.drop_index('ix_kpi_investment')

    op.drop_table('investment_kpis')
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.drop_index('ix_catalyst_investment')
        batch_op.drop_index('ix_catalyst_expected')

    op.drop_table('catalysts')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index('ix_investment_status')
        batch_op.drop_index('ix_investment_next_review')
        batch_op.drop_index('ix_investment_instrument')

    op.drop_table('investments')
    # ### end Alembic commands ###
