"""intelligence layer

Revision ID: 0004_intelligence_layer
Revises: 0003_research_layer
Create Date: 2026-08-24 11:09:47.842403
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0004_intelligence_layer'
down_revision = '0003_research_layer'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', name='uq_manager_cik')
    )
    op.create_table('macro_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'series_code', name='uq_macro_series')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('entity_key', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('raw_path', sa.String(length=400), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=30), nullable=True),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'source_type', 'external_id', name='uq_srcdoc_provider_ext')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index('ix_srcdoc_entity', ['entity_key'], unique=False)
        batch_op.create_index('ix_srcdoc_published', ['published_at'], unique=False)
        batch_op.create_index('ix_srcdoc_sha', ['sha256'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'key', name='uq_watchlist_kind_key')
    )
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('taxonomy', sa.String(length=30), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('is_instant', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=10), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('accession', sa.String(length=30), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=True),
    sa.Column('fact_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_hash', name='uq_fact_hash')
    )
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.create_index('ix_fact_cik_concept', ['cik', 'concept'], unique=False)
        batch_op.create_index('ix_fact_metric', ['metric'], unique=False)
        batch_op.create_index('ix_fact_period_end', ['period_end'], unique=False)

    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('cusip', sa.String(length=20), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['institutional_managers.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'period', 'cusip', name='uq_holding_mgr_period_cusip')
    )
    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.create_index('ix_holding_cusip', ['cusip'], unique=False)
        batch_op.create_index('ix_holding_period', ['period'], unique=False)

    op.create_table('macro_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'obs_date', 'value', name='uq_macro_obs')
    )
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.create_index('ix_macro_obs_series_date', ['series_id', 'obs_date'], unique=False)

    op.create_table('congress_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('asset_description', sa.String(length=400), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=True),
    sa.Column('amount_low', sa.Float(), nullable=True),
    sa.Column('amount_high', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_congress_dedup')
    )
    with op.batch_alter_table('congress_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_congress_person', ['person'], unique=False)
        batch_op.create_index('ix_congress_ticker', ['ticker'], unique=False)

    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_cik', sa.String(length=20), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('insider_name', sa.String(length=200), nullable=False),
    sa.Column('insider_role', sa.String(length=200), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('security', sa.String(length=200), nullable=True),
    sa.Column('transaction_code', sa.String(length=5), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('shares_after', sa.Float(), nullable=True),
    sa.Column('direct_ownership', sa.Boolean(), nullable=True),
    sa.Column('acquired_disposed', sa.String(length=1), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_insider_dedup')
    )
    with op.batch_alter_table('insider_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_insider_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_insider_issuer_date', ['issuer_cik', 'transaction_date'], unique=False)

    op.create_table('intelligence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('materiality_source', sa.String(length=15), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=False),
    sa.Column('processing_state', sa.String(length=15), nullable=False),
    sa.Column('ai_state', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_event_dedup')
    )
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_event_state', ['processing_state'], unique=False)
        batch_op.create_index('ix_event_type_time', ['event_type', 'occurred_at'], unique=False)

    op.create_table('investment_macro_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=200), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('expected_direction', sa.String(length=100), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id', 'series_id', name='uq_inv_macro')
    )
    op.create_table('research_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_investment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'source', name='uq_candidate_ticker_source')
    )
    with op.batch_alter_table('research_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_status', ['status'], unique=False)

    op.create_table('ai_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_type', sa.String(length=30), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('what_happened', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('proposed_change_json', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('supporting_refs', sa.Text(), nullable=True),
    sa.Column('contradicting_refs', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['intelligence_events.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_proposal_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_status')
        batch_op.drop_index('ix_proposal_investment')

    op.drop_table('ai_proposals')
    with op.batch_alter_table('research_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_status')

    op.drop_table('research_candidates')
    op.drop_table('investment_macro_links')
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_time')
        batch_op.drop_index('ix_event_state')
        batch_op.drop_index('ix_event_investment')

    op.drop_table('intelligence_events')
    with op.batch_alter_table('insider_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_insider_issuer_date')
        batch_op.drop_index('ix_insider_investment')

    op.drop_table('insider_transactions')
    with op.batch_alter_table('congress_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_congress_ticker')
        batch_op.drop_index('ix_congress_person')

    op.drop_table('congress_transactions')
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_macro_obs_series_date')

    op.drop_table('macro_observations')
    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_holding_period')
        batch_op.drop_index('ix_holding_cusip')

    op.drop_table('institutional_holdings')
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_period_end')
        batch_op.drop_index('ix_fact_metric')
        batch_op.drop_index('ix_fact_cik_concept')

    op.drop_table('financial_facts')
    op.drop_table('watchlist_entries')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_srcdoc_sha')
        batch_op.drop_index('ix_srcdoc_published')
        batch_op.drop_index('ix_srcdoc_entity')

    op.drop_table('source_documents')
    op.drop_table('macro_series')
    op.drop_table('institutional_managers')
    # ### end Alembic commands ###
