"""mentor briefing

Revision ID: 0005_mentor_briefing
Revises: 0004_intelligence_layer
Create Date: 2026-08-25 09:24:23.148518
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0005_mentor_briefing'
down_revision = '0004_intelligence_layer'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_type', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=50), nullable=True),
    sa.Column('ai_context_hash', sa.String(length=64), nullable=True),
    sa.Column('output_path', sa.String(length=400), nullable=True),
    sa.Column('audio_path', sa.String(length=400), nullable=True),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('portfolio_state_json', sa.Text(), nullable=True),
    sa.Column('research_state_hash', sa.String(length=64), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('suppressed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief_runs', schema=None) as batch_op:
        batch_op.create_index('ix_brief_run_period_end', ['period_end'], unique=False)
        batch_op.create_index('ix_brief_run_type_status', ['brief_type', 'status'], unique=False)

    op.create_table('attention_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('defer_until', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('first_surfaced_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key', name='uq_attention_item_key')
    )
    op.create_table('brief_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_run_id', sa.Integer(), nullable=False),
    sa.Column('delta_type', sa.String(length=40), nullable=False),
    sa.Column('item_key', sa.String(length=160), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_refs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_run_id'], ['brief_runs.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief_items', schema=None) as batch_op:
        batch_op.create_index('ix_brief_item_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_brief_item_key', ['item_key'], unique=False)
        batch_op.create_index('ix_brief_item_run', ['brief_run_id'], unique=False)

    op.create_table('management_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('time_horizon', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.String(length=400), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('management_claims', schema=None) as batch_op:
        batch_op.create_index('ix_claim_investment', ['investment_id'], unique=False)
        batch_op.create_index('ix_claim_status', ['status'], unique=False)

    op.create_table('brief_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_item_id', sa.Integer(), nullable=True),
    sa.Column('item_key', sa.String(length=160), nullable=False),
    sa.Column('rating', sa.String(length=15), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_item_id'], ['brief_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_item_key', ['item_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_item_key')

    op.drop_table('brief_feedback')
    with op.batch_alter_table('management_claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_status')
        batch_op.drop_index('ix_claim_investment')

    op.drop_table('management_claims')
    with op.batch_alter_table('brief_items', schema=None) as batch_op:
        batch_op.drop_index('ix_brief_item_run')
        batch_op.drop_index('ix_brief_item_key')
        batch_op.drop_index('ix_brief_item_investment')

    op.drop_table('brief_items')
    op.drop_table('attention_states')
    with op.batch_alter_table('brief_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_brief_run_type_status')
        batch_op.drop_index('ix_brief_run_period_end')

    op.drop_table('brief_runs')
    # ### end Alembic commands ###
