"""v5 operations mentor

Revision ID: 0006_v5_operations_mentor
Revises: 0005_mentor_briefing
Create Date: 2026-08-25 10:16:23.560568
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0006_v5_operations_mentor'
down_revision = '0005_mentor_briefing'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('output_path', sa.String(length=400), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_run_type', ['pipeline', 'started_at'], unique=False)

    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_run_name', ['name'], unique=False)

    op.create_table('concept_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('brief_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brief_run_id'], ['brief_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_stage_run', ['run_id'], unique=False)

    op.create_table('claim_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['management_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_links', schema=None) as batch_op:
        batch_op.create_index('ix_claim_link_claim', ['claim_id'], unique=False)

    op.create_table('decision_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.String(length=15), nullable=False),
    sa.Column('would_repeat', sa.Boolean(), nullable=True),
    sa.Column('replay_used', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_decision_review_decision', ['decision_id'], unique=False)

    with op.batch_alter_table('management_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('claim_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('stated_confidence', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('management_claims', schema=None) as batch_op:
        batch_op.drop_column('stated_confidence')
        batch_op.drop_column('claim_type')
        batch_op.drop_column('speaker_role')

    with op.batch_alter_table('decision_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_review_decision')

    op.drop_table('decision_reviews')
    with op.batch_alter_table('claim_links', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_link_claim')

    op.drop_table('claim_links')
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_stage_run')

    op.drop_table('pipeline_stages')
    op.drop_table('concept_history')
    with op.batch_alter_table('scenario_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_run_name')

    op.drop_table('scenario_runs')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_run_type')

    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
